import Foundation

struct Event: Identifiable, Codable, Hashable {
    var id: String
    var title: String
    var type: EventType
    var description: String
    var location: String
    var coordinates: GeoPoint?
    var dateTime: Date
    var endDateTime: Date?
    var registrationURL: String?
    var registrationDeadline: Date?
    var isPro: Bool
    var isWomenOnly: Bool
    var organizer: String
    var organizerId: String
    var maxParticipants: Int?
    var currentParticipants: Int
    var entryFee: Double?
    var prizePool: String?
    var bannerURL: String?
    var tags: [String]
    var isRegistered: Bool
}

extension Event {
    static let mockEvents: [Event] = [
        Event(id: "evt_001", title: "Austin Open Pickleball Tournament",
              type: .tournament, description: "Annual open tournament featuring singles, doubles, and mixed doubles brackets for all skill levels 3.0–5.0+.",
              location: "Westside Pickleball Complex, Austin TX",
              coordinates: GeoPoint(latitude: 30.2889, longitude: -97.7681),
              dateTime: Calendar.current.date(byAdding: .day, value: 14, to: Date()) ?? Date(),
              endDateTime: Calendar.current.date(byAdding: .day, value: 15, to: Date()),
              registrationURL: "https://example.com/austin-open",
              registrationDeadline: Calendar.current.date(byAdding: .day, value: 7, to: Date()),
              isPro: false, isWomenOnly: false, organizer: "Austin Pickleball Alliance",
              organizerId: "club_001", maxParticipants: 256, currentParticipants: 178,
              entryFee: 45.00, prizePool: "$5,000", bannerURL: nil,
              tags: ["tournament", "austin", "allskills"], isRegistered: true),
        Event(id: "evt_002", title: "Women's Beginner Clinic",
              type: .clinic, description: "A supportive 3-hour clinic designed specifically for women new to pickleball. Certified instructor. Equipment provided.",
              location: "Mueller Recreation Center, Austin TX",
              coordinates: GeoPoint(latitude: 30.3042, longitude: -97.7024),
              dateTime: Calendar.current.date(byAdding: .day, value: 5, to: Date()) ?? Date(),
              endDateTime: nil, registrationURL: nil, registrationDeadline: nil,
              isPro: false, isWomenOnly: true, organizer: "ATX Women's Pickleball",
              organizerId: "club_002", maxParticipants: 20, currentParticipants: 14,
              entryFee: 25.00, prizePool: nil, bannerURL: nil,
              tags: ["clinic", "womens", "beginner"], isRegistered: false),
        Event(id: "evt_003", title: "Friday Night Social Mixer",
              type: .social, description: "Casual open play social every Friday evening. Food trucks on site. All skill levels welcome.",
              location: "South Lamar Sports Club, Austin TX",
              coordinates: GeoPoint(latitude: 30.2473, longitude: -97.7528),
              dateTime: Calendar.current.date(byAdding: .day, value: 2, to: Date()) ?? Date(),
              endDateTime: nil, registrationURL: nil, registrationDeadline: nil,
              isPro: false, isWomenOnly: false, organizer: "South Lamar Sports Club",
              organizerId: "club_003", maxParticipants: 80, currentParticipants: 52,
              entryFee: 10.00, prizePool: nil, bannerURL: nil,
              tags: ["social", "openplay", "friday"], isRegistered: false),
        Event(id: "evt_004", title: "4.0+ Competitive Ladder",
              type: .tournament, description: "Weekly competitive ladder play for serious 4.0+ players. Rotating partners, ELO-style ranking system. Shows up in your Dinkr ranking.",
              location: "Westside Pickleball Complex, Austin TX",
              coordinates: GeoPoint(latitude: 30.2889, longitude: -97.7681),
              dateTime: Calendar.current.date(byAdding: .day, value: 3, to: Date()) ?? Date(),
              endDateTime: nil, registrationURL: nil, registrationDeadline: Calendar.current.date(byAdding: .day, value: 2, to: Date()),
              isPro: false, isWomenOnly: false, organizer: "Austin Competitive Pickleball",
              organizerId: "club_001", maxParticipants: 32, currentParticipants: 21,
              entryFee: 15.00, prizePool: nil, bannerURL: nil,
              tags: ["competitive", "ladder", "4point0"], isRegistered: true),
        Event(id: "evt_005", title: "Sunday Morning Open Play Social",
              type: .social, description: "Casual open play every Sunday morning at Mueller. Food trucks, good vibes, all skill levels. Doors open at 7:30am.",
              location: "Mueller Recreation Center, Austin TX",
              coordinates: GeoPoint(latitude: 30.3042, longitude: -97.7024),
              dateTime: Calendar.current.date(byAdding: .day, value: 4, to: Date()) ?? Date(),
              endDateTime: nil, registrationURL: nil, registrationDeadline: nil,
              isPro: false, isWomenOnly: false, organizer: "Mueller Park Community",
              organizerId: "club_003", maxParticipants: 60, currentParticipants: 38,
              entryFee: 0.00, prizePool: nil, bannerURL: nil,
              tags: ["social", "openplay", "sunday"], isRegistered: false),
        Event(id: "evt_006", title: "Pickleball 101 — Beginner Workshop",
              type: .clinic, description: "A friendly 2-hour intro workshop. No equipment needed — paddles and balls provided. Perfect for absolute beginners.",
              location: "South Lamar Sports Club, Austin TX",
              coordinates: GeoPoint(latitude: 30.2473, longitude: -97.7528),
              dateTime: Calendar.current.date(byAdding: .day, value: 8, to: Date()) ?? Date(),
              endDateTime: nil, registrationURL: nil, registrationDeadline: Calendar.current.date(byAdding: .day, value: 7, to: Date()),
              isPro: false, isWomenOnly: false, organizer: "South Lamar Sports Club",
              organizerId: "club_003", maxParticipants: 15, currentParticipants: 6,
              entryFee: 20.00, prizePool: nil, bannerURL: nil,
              tags: ["beginner", "clinic", "intro"], isRegistered: false),
        Event(id: "evt_007", title: "ATX Charity Pickleball Fundraiser",
              type: .fundraiser, description: "Annual charity tournament supporting Austin youth sports programs. Round robin format, prizes for top teams, silent auction on site.",
              location: "Zilker Park Courts, Austin TX",
              coordinates: GeoPoint(latitude: 30.2672, longitude: -97.7731),
              dateTime: Calendar.current.date(byAdding: .day, value: 21, to: Date()) ?? Date(),
              endDateTime: Calendar.current.date(byAdding: .day, value: 21, to: Date()),
              registrationURL: "https://example.com/charity",
              registrationDeadline: Calendar.current.date(byAdding: .day, value: 14, to: Date()),
              isPro: false, isWomenOnly: false, organizer: "Austin Community Foundation",
              organizerId: "club_001", maxParticipants: 128, currentParticipants: 84,
              entryFee: 50.00, prizePool: "Charity Prizes", bannerURL: nil,
              tags: ["charity", "fundraiser", "community"], isRegistered: false),
        Event(id: "evt_008", title: "Women's 3.5 Round Robin",
              type: .womenOnly, description: "Competitive round robin exclusively for women's 3.5 players. Excellent for DUPR tracking and finding regular partners.",
              location: "Barton Springs Tennis Center, Austin TX",
              coordinates: GeoPoint(latitude: 30.2502, longitude: -97.7720),
              dateTime: Calendar.current.date(byAdding: .day, value: 10, to: Date()) ?? Date(),
              endDateTime: nil, registrationURL: nil,
              registrationDeadline: Calendar.current.date(byAdding: .day, value: 8, to: Date()),
              isPro: false, isWomenOnly: true, organizer: "ATX Women's Pickleball",
              organizerId: "club_002", maxParticipants: 24, currentParticipants: 18,
              entryFee: 20.00, prizePool: nil, bannerURL: nil,
              tags: ["womens", "roundrobin", "3.5"], isRegistered: false),
        Event(id: "evt_009", title: "Advanced Doubles Strategy Clinic",
              type: .clinic, description: "4.0+ clinic taught by pro Derek Martinez covering stacking formations, ATP positioning, speed-up drills, and kitchen line communication. Limited to 16 players. Bring a partner or we'll pair you up.",
              location: "Westside Pickleball Complex, Austin TX",
              coordinates: GeoPoint(latitude: 30.2889, longitude: -97.7681),
              dateTime: Calendar.current.date(byAdding: .day, value: 6, to: Date()) ?? Date(),
              endDateTime: Calendar.current.date(byAdding: .day, value: 6, to: Date()),
              registrationURL: "https://example.com/advanced-clinic",
              registrationDeadline: Calendar.current.date(byAdding: .day, value: 4, to: Date()),
              isPro: true, isWomenOnly: false, organizer: "Derek Martinez Coaching",
              organizerId: "club_001", maxParticipants: 16, currentParticipants: 12,
              entryFee: 75.00, prizePool: nil, bannerURL: nil,
              tags: ["clinic", "advanced", "coaching", "4point0"], isRegistered: false),
        Event(id: "evt_010", title: "Georgetown Open — Spring Classic",
              type: .tournament, description: "Two-day tournament at the newly expanded Georgetown Recreation Center. Brackets for 2.5, 3.0, 3.5, and 4.0+. Mixed doubles and singles. Cash prizes for 4.0+ division winners.",
              location: "Georgetown Recreation Center, Georgetown TX",
              coordinates: GeoPoint(latitude: 30.6208, longitude: -97.6783),
              dateTime: Calendar.current.date(byAdding: .day, value: 28, to: Date()) ?? Date(),
              endDateTime: Calendar.current.date(byAdding: .day, value: 29, to: Date()),
              registrationURL: "https://example.com/georgetown-open",
              registrationDeadline: Calendar.current.date(byAdding: .day, value: 21, to: Date()),
              isPro: false, isWomenOnly: false, organizer: "Georgetown Parks & Rec",
              organizerId: "club_001", maxParticipants: 192, currentParticipants: 114,
              entryFee: 40.00, prizePool: "$2,500", bannerURL: nil,
              tags: ["tournament", "georgetown", "allskills", "spring"], isRegistered: false),
        Event(id: "evt_011", title: "Twilight Open Play — Pflugerville",
              type: .openPlay, description: "Evening open play under the lights at Pflugerville Community Park. Rotating partners, skill-matched games. Bring your own water and a good attitude. No registration required — just show up!",
              location: "Pflugerville Community Park, Pflugerville TX",
              coordinates: GeoPoint(latitude: 30.4393, longitude: -97.6200),
              dateTime: Calendar.current.date(byAdding: .day, value: 1, to: Date()) ?? Date(),
              endDateTime: nil, registrationURL: nil, registrationDeadline: nil,
              isPro: false, isWomenOnly: false, organizer: "Pflugerville Pickle Club",
              organizerId: "club_003", maxParticipants: 40, currentParticipants: 27,
              entryFee: 5.00, prizePool: nil, bannerURL: nil,
              tags: ["openplay", "pflugerville", "evening"], isRegistered: true),
        Event(id: "evt_012", title: "ATX Women's Social & Clinic",
              type: .womenOnly, description: "Monthly women's social combining a 45-minute skills clinic with two hours of structured open play. This month's focus: third-shot drop mechanics. All skill levels 2.5–4.0. Light refreshments provided.",
              location: "Mueller Recreation Center, Austin TX",
              coordinates: GeoPoint(latitude: 30.3042, longitude: -97.7024),
              dateTime: Calendar.current.date(byAdding: .day, value: 12, to: Date()) ?? Date(),
              endDateTime: nil, registrationURL: nil,
              registrationDeadline: Calendar.current.date(byAdding: .day, value: 10, to: Date()),
              isPro: false, isWomenOnly: true, organizer: "ATX Women's Pickleball",
              organizerId: "club_002", maxParticipants: 30, currentParticipants: 22,
              entryFee: 15.00, prizePool: nil, bannerURL: nil,
              tags: ["womens", "social", "clinic", "monthly"], isRegistered: false),
        Event(id: "evt_013", title: "Beginner Bootcamp Weekend",
              type: .clinic, description: "Full-weekend immersive bootcamp for true beginners (2.0–2.5). Saturday covers fundamentals — scoring, serving, basic strokes. Sunday introduces the kitchen game and doubles strategy. Equipment provided. Space limited to 12.",
              location: "South Lamar Sports Club, Austin TX",
              coordinates: GeoPoint(latitude: 30.2473, longitude: -97.7528),
              dateTime: Calendar.current.date(byAdding: .day, value: -3, to: Date()) ?? Date(),
              endDateTime: Calendar.current.date(byAdding: .day, value: -2, to: Date()),
              registrationURL: "https://example.com/bootcamp",
              registrationDeadline: Calendar.current.date(byAdding: .day, value: -5, to: Date()),
              isPro: false, isWomenOnly: false, organizer: "South Lamar Sports Club",
              organizerId: "club_003", maxParticipants: 12, currentParticipants: 12,
              entryFee: 60.00, prizePool: nil, bannerURL: nil,
              tags: ["beginner", "bootcamp", "clinic", "weekend"], isRegistered: false),
    ]
}
