import Foundation

struct MarketListing: Identifiable, Codable, Hashable {
    var id: String
    var sellerId: String
    var sellerName: String
    var category: MarketCategory
    var brand: String
    var model: String
    var condition: ListingCondition
    var price: Double
    var description: String
    var photos: [String]
    var status: ListingStatus
    var location: String
    var createdAt: Date
    var isFeatured: Bool
    var viewCount: Int
}

extension MarketListing {
    static let mockListings: [MarketListing] = [
        MarketListing(id: "ml_001", sellerId: "user_005", sellerName: "Chris Park",
                      category: .paddles, brand: "Selkirk", model: "Vanguard Power Air",
                      condition: .likeNew, price: 185.00,
                      description: "Used for 3 months. Small scuff on edge guard but plays perfectly. Original grip still on. Comes with cover.",
                      photos: [], status: .active, location: "Austin, TX",
                      createdAt: Date().addingTimeInterval(-86400), isFeatured: true, viewCount: 47),
        MarketListing(id: "ml_002", sellerId: "user_006", sellerName: "Taylor Kim",
                      category: .paddles, brand: "JOOLA", model: "Ben Johns Hyperion CAS 16",
                      condition: .good, price: 120.00,
                      description: "Great paddle, upgrading to a newer model. Light scratches but fully functional. Grip has been replaced.",
                      photos: [], status: .active, location: "Round Rock, TX",
                      createdAt: Date().addingTimeInterval(-172800), isFeatured: false, viewCount: 31),
        MarketListing(id: "ml_003", sellerId: "user_007", sellerName: "Jamie Lee",
                      category: .bags, brand: "HEAD", model: "Tour Team Backpack",
                      condition: .brandNew, price: 65.00,
                      description: "Never used. Gift I received that doesn't fit my style. Tags still on.",
                      photos: [], status: .active, location: "Cedar Park, TX",
                      createdAt: Date().addingTimeInterval(-43200), isFeatured: false, viewCount: 18),
        MarketListing(id: "ml_004", sellerId: "user_008", sellerName: "Morgan Davis",
                      category: .shoes, brand: "K-Swiss", model: "Hypercourt Express 2 HB",
                      condition: .good, price: 55.00,
                      description: "Size 10.5. Great court shoes, only used one season. Normal wear on soles.",
                      photos: [], status: .active, location: "Austin, TX",
                      createdAt: Date().addingTimeInterval(-259200), isFeatured: false, viewCount: 22),
        MarketListing(id: "ml_005", sellerId: "user_002", sellerName: "Maria Chen",
                      category: .apparel, brand: "Prince", model: "Women's Court Tank",
                      condition: .likeNew, price: 28.00,
                      description: "Wore twice, perfect condition. Size M. Breathable fabric, great for outdoor play.",
                      photos: [], status: .active, location: "Austin, TX",
                      createdAt: Date().addingTimeInterval(-21600), isFeatured: false, viewCount: 15),
        MarketListing(id: "ml_006", sellerId: "user_007", sellerName: "Jamie Lee",
                      category: .paddles, brand: "Franklin", model: "Ben Johns Signature",
                      condition: .good, price: 95.00,
                      description: "Intermediate paddle, great for 3.0–3.5 players. Upgrading to pro-level. Has sticker on back.",
                      photos: [], status: .active, location: "Austin, TX",
                      createdAt: Date().addingTimeInterval(-108000), isFeatured: false, viewCount: 67),
        MarketListing(id: "ml_007", sellerId: "user_003", sellerName: "Jordan Smith",
                      category: .balls, brand: "ONIX", model: "Pure 2 Outdoor 6-Pack",
                      condition: .brandNew, price: 22.00,
                      description: "Never opened. Received as gift, already have plenty. USAPA approved.",
                      photos: [], status: .active, location: "Austin, TX",
                      createdAt: Date().addingTimeInterval(-32400), isFeatured: false, viewCount: 9),
        MarketListing(id: "ml_008", sellerId: "user_009", sellerName: "Riley Torres",
                      category: .accessories, brand: "Gamma", model: "Overgrip 30-Pack",
                      condition: .brandNew, price: 18.00,
                      description: "Unopened 30-pack of overgrips. Great deal — bought too many.",
                      photos: [], status: .active, location: "Austin, TX",
                      createdAt: Date().addingTimeInterval(-64800), isFeatured: false, viewCount: 24),
        MarketListing(id: "ml_009", sellerId: "user_005", sellerName: "Chris Park",
                      category: .paddles, brand: "Electrum", model: "Model E Pro",
                      condition: .likeNew, price: 210.00,
                      description: "Used for one month. Pro-level paddle, slight edge wear but surface pristine. Comes with original sleeve.",
                      photos: [], status: .active, location: "Round Rock, TX",
                      createdAt: Date().addingTimeInterval(-7200), isFeatured: true, viewCount: 89),
        MarketListing(id: "ml_010", sellerId: "user_008", sellerName: "Morgan Davis",
                      category: .shoes, brand: "New Balance", model: "MC806v1",
                      condition: .good, price: 48.00,
                      description: "Size 9 women's. Worn one season, still plenty of life left. Great lateral support.",
                      photos: [], status: .active, location: "Austin, TX",
                      createdAt: Date().addingTimeInterval(-129600), isFeatured: false, viewCount: 31),
        // Recently added (within last 7 days)
        MarketListing(id: "ml_011", sellerId: "user_004", sellerName: "Alex Rivera",
                      category: .paddles, brand: "Paddletek", model: "Bantam EX-L Pro",
                      condition: .likeNew, price: 145.00,
                      description: "Purchased 2 weeks ago, switching to a lighter paddle. Surface is pristine.",
                      photos: [], status: .active, location: "Austin, TX",
                      createdAt: Date().addingTimeInterval(-86400 * 2), isFeatured: false, viewCount: 12),
        MarketListing(id: "ml_012", sellerId: "user_003", sellerName: "Jordan Smith",
                      category: .accessories, brand: "Tourna", model: "Grip Original XL",
                      condition: .brandNew, price: 12.00,
                      description: "Three packs, brand new. Bought in bulk.",
                      photos: [], status: .active, location: "Round Rock, TX",
                      createdAt: Date().addingTimeInterval(-86400 * 1), isFeatured: false, viewCount: 5),
        // Sold listings
        MarketListing(id: "ml_013", sellerId: "user_002", sellerName: "Maria Chen",
                      category: .paddles, brand: "Engage", model: "Pursuit Ultra",
                      condition: .good, price: 130.00,
                      description: "Sold! Great paddle for control players.",
                      photos: [], status: .sold, location: "Austin, TX",
                      createdAt: Date().addingTimeInterval(-86400 * 5), isFeatured: false, viewCount: 44),
        MarketListing(id: "ml_014", sellerId: "user_006", sellerName: "Taylor Kim",
                      category: .bags, brand: "Prokennex", model: "Pro Speed Bag",
                      condition: .likeNew, price: 75.00,
                      description: "Sold! Barely used, great condition.",
                      photos: [], status: .sold, location: "Austin, TX",
                      createdAt: Date().addingTimeInterval(-86400 * 8), isFeatured: false, viewCount: 29),
        MarketListing(id: "ml_015", sellerId: "user_009", sellerName: "Riley Torres",
                      category: .shoes, brand: "Asics", model: "Gel-Rocket 10",
                      condition: .good, price: 42.00,
                      description: "Sold! Size 11, solid indoor/outdoor court shoe.",
                      photos: [], status: .sold, location: "Cedar Park, TX",
                      createdAt: Date().addingTimeInterval(-86400 * 3), isFeatured: false, viewCount: 19),
        // New listings
        MarketListing(id: "ml_016", sellerId: "user_011", sellerName: "Priya Patel",
                      category: .paddles, brand: "Selkirk", model: "Vanguard Power Air Epic",
                      condition: .likeNew, price: 195.00,
                      description: "Upgrading to the Vanguard 2. This paddle is in near-perfect shape — played about 40 sessions. Slightly rough surface for spin, fast swing weight. Comes with Selkirk sleeve.",
                      photos: [], status: .active, location: "Austin, TX",
                      createdAt: Date().addingTimeInterval(-86400 * 1), isFeatured: true, viewCount: 62),
        MarketListing(id: "ml_017", sellerId: "user_012", sellerName: "Marcus Williams",
                      category: .paddles, brand: "JOOLA", model: "Ben Johns Hyperion CFS 16",
                      condition: .good, price: 140.00,
                      description: "Ben Johns signature CFS — used for one full season of competitive 4.5 play. Some face scuffs but nothing affecting performance. Original grip. Great for control players.",
                      photos: [], status: .active, location: "Pflugerville, TX",
                      createdAt: Date().addingTimeInterval(-86400 * 4), isFeatured: false, viewCount: 78),
        MarketListing(id: "ml_018", sellerId: "user_013", sellerName: "Sophie Chen",
                      category: .balls, brand: "Franklin", model: "X-40 Outdoor 12-Pack",
                      condition: .brandNew, price: 32.00,
                      description: "Sealed 12-pack of Franklin X-40 outdoor balls. USAPA approved and used at most local tournaments. Bought two packs, only need one.",
                      photos: [], status: .active, location: "Austin, TX",
                      createdAt: Date().addingTimeInterval(-86400 * 2), isFeatured: false, viewCount: 21),
        MarketListing(id: "ml_019", sellerId: "user_014", sellerName: "Derek Martinez",
                      category: .bags, brand: "Selkirk", model: "Pro Backpack XL",
                      condition: .likeNew, price: 85.00,
                      description: "Holds 4 paddles plus full kit. Used for a few tournaments before I got a sponsor bag. Excellent condition. All zippers work perfectly, no tears.",
                      photos: [], status: .active, location: "Austin, TX",
                      createdAt: Date().addingTimeInterval(-3600 * 8), isFeatured: true, viewCount: 104),
        MarketListing(id: "ml_020", sellerId: "user_015", sellerName: "Aisha Johnson",
                      category: .apparel, brand: "Lululemon", model: "Pace Rival Skirt (Court Edition)",
                      condition: .likeNew, price: 45.00,
                      description: "Size 6. Wore twice, perfect condition. Built-in shorts with ball pocket. Great for outdoor play — sweat-wicking and moves well.",
                      photos: [], status: .active, location: "Austin, TX",
                      createdAt: Date().addingTimeInterval(-3600 * 18), isFeatured: false, viewCount: 33),
        MarketListing(id: "ml_021", sellerId: "user_016", sellerName: "Kevin Park",
                      category: .accessories, brand: "Fromuth", model: "Lead Tape + Edge Guard Kit",
                      condition: .brandNew, price: 14.00,
                      description: "Unopened customization kit — lead tape rolls and edge guard tape. Great for adding swing weight or head heaviness to any paddle.",
                      photos: [], status: .active, location: "Georgetown, TX",
                      createdAt: Date().addingTimeInterval(-3600 * 5), isFeatured: false, viewCount: 17),
        MarketListing(id: "ml_022", sellerId: "user_010", sellerName: "Tyler Brooks",
                      category: .paddles, brand: "Paddletek", model: "Tempest Wave Pro",
                      condition: .fair, price: 55.00,
                      description: "My first 'real' paddle — definitely has some battle scars but still plays fine. Great starter paddle for 2.0–3.0 players who want a step up from recreational boards.",
                      photos: [], status: .sold, location: "San Marcos, TX",
                      createdAt: Date().addingTimeInterval(-86400 * 6), isFeatured: false, viewCount: 38),
    ]
}
